# SmallRNA test config file  -*- conf -*-
name: SmallRNA::Web
long_name: SmallRNA tracking
pipeline_directory: /tmp/pipeline-test
data_sub_directory: test-results
"Model::SmallRNAModel":
    schema_class: 'SmallRNA::DB'
    connect_info:
       - "dbi:Pg:dbname=pipeline-test;host=localhost"
       - 'kmr44'
       - 'kmr'
programs:
  ssaha:
    path: /applications/ssaha_v31c_amd64/ssaha_v31c_amd64
    process_class: SmallRNA::Process::SSAHASearchProcess
  patman:
    path: /applications/patman-1.2.1/patman
    process_class: SmallRNA::Process::PatmanAlignmentProcess
  bwa:
    path: /applications/bwa/bwa-0.4.9/bwa
    process_class: SmallRNA::Process::BWASearchProcess
  samtools:
    path: /applications/samtools-svn-trunk/samtools/samtools
  srf2fastq:
    path: /applications/io_lib-1-12-1/progs/srf2fastq
databases:
  root: t/data
  organisms:
    Arabidopsis_thaliana:
      database_files:
        genome: arabidopsis_thaliana_test_genome.fasta
        trna: arabidopsis_thaliana_test_trnas.fasta
    Chlamydomonas_reinhardtii:
      database_files:
        genome: chlamydomonas_reinhardtii_test_genome.fasta
